public class App {
    public static void main(String[] args) {
        try {

        } finally {

        }
    }
}

// Si, la sintaxis es valida
// En caso de lanzarse una excepcion en el try
// El finally se ejecutaria antes de salir de la funcion, aunque no haya un bloque catch
